version: '2.4'

services:
  db:
    build:
      context: ./db
    image: swipen-db/swipen-db:dev
    ports:
      - 3370:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: $MYSQL_USERNAME_SWIPEN
      MYSQL_PASSWORD: $MYSQL_PASSWORD_SWIPEN
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  application:
    build:
      context: ../application
      target: dev
    # Debugging port for SS
    ports:
      - 9007:9229
      - 8080:8080
    image: swipen-be/application:dev
    environment:
      MYSQL_USERNAME: $MYSQL_USERNAME_SWIPEN
      MYSQL_PASSWORD: $MYSQL_PASSWORD_SWIPEN
      MYSQL_DATABASE: $MYSQL_DATABASE_SWIPEN
      MYSQL_HOST: $MYSQL_HOST_SWIPEN
      MODE: TEST
      AWS_PROFILE: swipen-dev
      AWS_REGION: eu-west-2
      AWS_API_VERSION: '2012-11-05'
      AWS_SWIPEN_BUCKET: $AWS_SWIPEN_DEV_BUCKET
    volumes:
      - ../application:/app:delegated
      - $HOME/.aws:/root/.aws
    healthcheck:
          test: ["CMD", "curl", "http://localhost:8080/healthz"]
          timeout: 3s
          retries: 3
    depends_on:
      db:
        condition: service_healthy


volumes:
  db:
